%YAML 1.2
---

# for adversary chatbot
bert_model_name: /home/pzhu/data/bert/bert-base-uncased
dialog_file: data/babi/babi_adversary.xlsx 
batch_size: 50
use_gpu: 1
min_score: 0.6 #jump the rule if less than this score

hook_keywords:
    PARTY_SIZE: data/babi/entities/party_size.txt
    LOCATION: data/babi/entities/location.txt
    CUISINE: data/babi/entities/cuisine.txt
    REST_TYPE: data/babi/entities/rest_type.txt

logger:
    appname: babi
    loglevel_console:  10
    loglevel_file: 0
    logfile: data/babi/train.log
