version: '3'

services:

  elsa_bot:
      image: localhost:elsa_chatbot:latest
      restart: always
      ports:
          - 5000:5000
      volumes:
          - ../config:/opt/chatbot/config
          - ../data:/opt/chatbot/data
      working_dir: /opt/chatbot
      environment:
          BOT_CONFIG: config/FAQs.yml
