%YAML 1.2
---
#app setting
APPNAME: END2END_DEMO

response_template: 
    data: data/babi/template.txt
    cached_index: data/babi/template.index
    cached_vocab: data/babi/vocab_template.pkl
    vocab_size: 100000
    ngrams: 3

entity_dict: data/babi/entity.dict
max_entity_types: 5

ner:
    LANGUAGE: en
    TOKENIZER: spacy
    w2v_word2idx: /home/pzhu/data/word2vec/en/word2idx_2000000.pp
    w2v_idx2vec: /home/pzhu/data/word2vec/en/weight_2000000.npy
    cached_vocab: data/babi/vocab.pkl
    vocab_size: 100000
    cached_w2v: data/babi/w2v.pkl
    vec_len: 300
    annoy_filter: 0.8
    stopwords_path: config/en_stopwords.txt
    ner_name_replace:
    ner:
    keywords:
        PARTY_SIZE: data/babi/entities/party_size.txt
        LOCATION: data/babi/entities/location.txt
        CUISINE: data/babi/entities/cuisine.txt
        REST_TYPE: data/babi/entities/rest_type.txt
    regex:  
        REST_INFO: 'resto_\w*'


model:
    use_gpu: 1
    max_seq_len: 10
    dropout: 0
    cnn_kernel_size: 5
    cnn_kernel_num: 16
    learning_rate: 0.001
    weight_decay: 0.0001
    epochs: 100000
    batch_size: 1000
    saved_model: 'data/babi/model.pt'

logger:
    LogLevel_Console:  10
    LogLevel_File: 0
    LogFile: data/babi/train.log
    LogFormat: '%(asctime)s | %(levelname)s: %(message)s'

