%YAML 1.2
---
#app setting


# for adversary chatbot
rule_based:
      
    hook_keywords:
        PARTY_SIZE: data/babi/entities/party_size.txt
        LOCATION: data/babi/entities/location.txt
        CUISINE: data/babi/entities/cuisine.txt
        REST_TYPE: data/babi/entities/rest_type.txt
    
    logger:
        appname: ad_babi
        loglevel_console:  20
        loglevel_file: 0
        logfile: data/babi/train.log
    
    bert_model_name: /home/pzhu/data/bert/bert-base-uncased
    dialog_file: data/babi/babi_adversary.xlsx 
    batch_size: 50
    min_score: 0.6 #jump the rule if less than this score

#
response_template: data/babi/template.txt

ner:
    tokenizer: spacy
    ner_name_replace:
    ner:
    keywords:
        PARTY_SIZE: data/babi/entities/party_size.txt
        LOCATION: data/babi/entities/location.txt
        CUISINE: data/babi/entities/cuisine.txt
        REST_TYPE: data/babi/entities/rest_type.txt
    regex:  
        REST_INFO: 'resto_\w*'

tokenizer:
    bert_model_name: /home/pzhu/data/bert/bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

reader:
    train_data: /home/pzhu/data/dialog/babi/dialog-babi-task5-full-dialogs-trn.txt
    max_seq_len: 10

model:
    skill_name: babi
    device: "cuda:0"
    max_entity_types: 1024
    dropout: 0.8
    hidden_dim: 300
    entity_layers: 3
    entity_emb_dim: 50
    lstm_layers: 1
    learning_rate: 0.001
    weight_decay: 0.00001
    epochs: 10000
    batch_size: 2
    num_workers: 1
    saved_model: 'data/babi/model.pt'

reinforcement:
    learning_rate: 0.0001
    maxloop: 20
    discount: 0.95

logger:
    appname: babi
    loglevel_console:  20
    loglevel_file: 0
    logfile: data/babi/train.log

