%YAML 1.2
---
#app setting
APPNAME: END2END_DEMO


# for adversary chatbot
rule_based:
    
    tokenizer:
        bert_model_name: /home/pzhu/data/bert/bert-base-uncased
      
    embedding:
        w2v_word2idx: /home/pzhu/data/bert/bert-base-uncased/word2idx.zpkl
        w2v_idx2vec: /home/pzhu/data/bert/bert-base-uncased/word2vec_weight.npy
        dim: 768

    vocab:
        cached_vocab: data/babi/vocab_adversary.pkl

    hook_keywords:
        PARTY_SIZE: data/babi/entities/party_size.txt
        LOCATION: data/babi/entities/location.txt
        CUISINE: data/babi/entities/cuisine.txt
        REST_TYPE: data/babi/entities/rest_type.txt
    
    logger:
        LogLevel_Console:  20
        LogLevel_File: 0
        LogFile: data/babi/train.log
        LogFormat: '%(asctime)s | %(levelname)s: %(message)s'
    
    dialog_file: data/babi/babi_adversary.xlsx 
    min_score: 0.6 #jump the rule if less than this score

#
response_template: data/babi/template.txt

ner:
    tokenizer: spacy
    ner_name_replace:
    ner:
    keywords:
        PARTY_SIZE: data/babi/entities/party_size.txt
        LOCATION: data/babi/entities/location.txt
        CUISINE: data/babi/entities/cuisine.txt
        REST_TYPE: data/babi/entities/rest_type.txt
    regex:  
        REST_INFO: 'resto_\w*'

tokenizer:
    bert_model_name: /home/pzhu/data/bert/bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt


entity_dict:
    max_entity_types: 6
    entity_dict_path: data/babi/entity.dict

model:
    train_data: /home/pzhu/data/dialog/babi/dialog-babi-task5-full-dialogs-trn.txt
    use_gpu: 1
    max_seq_len: 10
    max_dialog_len: 20
    dropout: 0.8
    hidden_dim: 300
    fc_responses: 
        - 8
        - 8
    lstm_layers: 1
    learning_rate: 0.001
    weight_decay: 0.00001
    epochs: 10000
    batch_size: 50
    rl_learning_rate: 0.0001
    rl_maxloop: 20
    rl_discount: 0.95
    saved_model: 'data/babi/model.pt'

logger:
    appname: babi
    loglevel_console:  20
    loglevel_file: 0
    logfile: data/babi/train.log

