%YAML 1.2
---
#app setting


skill:
    name: babi
    wrapper: GoalResponse
    dialogflow: data/babi/babi.xlsx

hook:
    wrapper: Behaviors

ner:
    tokenizer: spacy

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1

reader:
    wrapper: ReaderBabi
    train_data: /home/pzhu/data/dialog/babi/dialog-babi-task5-full-dialogs-trn.txt
    max_seq_len: 20

model:
    device: "cuda:0"
    model_type: "transformer"
    encoder_hidden_layers: 3
    encoder_hidden_size: 768
    encoder_intermediate_size: 1024
    encoder_attention_heads: 3
    encoder_freeze: False

    max_entity_types: 512
    dropout: 0.8
    hidden_size: 1024
    entity_layers: 3
    entity_emb_dim: 50
    lstm_layers: 2
    learning_rate: 0.0001
    weight_decay: 0
    momentum: 0.9
    optimizer: "adam"
    epochs: 10000
    batch_size: 50
    num_workers: 1
    saved_model: 'data/babi/model.pt'
    save_per_epoch: 1

reinforcement:
    learning_rate: 0.0001
    maxloop: 20
    discount: 0.95

logger:
    appname: babi
    loglevel_console:  20
    loglevel_file: 0
    logfile: data/babi/train.log

