%YAML 1.2
---
#app setting

ner:
    tokenizer: spacy
    ner_name_replace:
    ner:
    keywords:
    regex:  

tokenizer:
    bert_model_name: /home/pzhu/data/bert/bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

reader:
    train_data: /home/pzhu/data/dialog/cornell_movie_dialogs_corpus
    max_seq_len: 10

model:
    skill_name: cornell
    device: "cuda:0"
    max_entity_types: 1024
    dropout: 0.8
    hidden_dim: 300
    entity_layers: 3
    entity_emb_dim: 50
    lstm_layers: 1
    learning_rate: 0.001
    weight_decay: 0.00001
    epochs: 10000
    batch_size: 2
    num_workers: 1
    saved_model: 'data/cornell/model.pt'

reinforcement:
    learning_rate: 0.0001
    maxloop: 20
    discount: 0.95

logger:
    appname: cornell
    loglevel_console:  20
    loglevel_file: 0
    logfile: data/cornell/train.log

