%YAML 1.2
---

#Config for elsa chatbot, interactive mode only

ner:
    tokenizer: spacy
    ner_name_replace:
    ner:
    keywords:
        PARTY_SIZE: data/babi/entities/party_size.txt
        LOCATION: data/babi/entities/location.txt
        CUISINE: data/babi/entities/cuisine.txt
        REST_TYPE: data/babi/entities/rest_type.txt
    regex:  
        REST_INFO: 'resto_\w*'

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

model:
    device: "cuda:0"
    max_seq_len: 50
    max_entity_types: 1024

skills:
    cornell: 
        wrapper: Generative_Response 
        saved_model: 'data/cornell/model.pt'

        #    babi: 
        #        wrapper: Goal_Response
        #        saved_model: 'data/babi/model.pt'
        #        template_file: data/babi/template.txt
        #        hook: 
        #            wrapper: Behaviors


logger:
    appname: elsa
    loglevel_console:  20
    loglevel_file: 0
    logfile: /tmp/elsa.log


