%YAML 1.2
---

#Config for elsa chatbot, interactive mode only

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

ner:
    tokenizer: spacy

backend:
    backend_type: telegram
    token: "670380934:AAHDxft69znEBLK_0z1G7uzv5obLEqFdndg"
    deepspeech:
        model: data/deepspeech/0.5.1/output_graph.pbmm
        alphabet: data/deepspeech/0.5.1/alphabet.txt
        lm: data/deepspeech/0.5.1/lm.binary
        trie: data/deepspeech/0.5.1/trie
    tts:
        tts_model: data/tts/checkpoint_261000.pth.tar
        tts_config: data/tts/config.json
        wavernn_model: data/wavernn/checkpoint_433000.pth.tar
        wavernn_config: data/wavernn/config.json
        device: "cuda:0"

topic_switch:
    strategy: queue # switch strategy, queue, current

timeout: 300 # seconds for session timeout

model:
    device: "cuda:0"
    max_seq_len: 20
    max_entity_types: 512

skills:
    cornell: 
        wrapper: RestResponse
        rest_url: http://192.168.1.112:5001/robot/api/query
        timeout: 3

