%YAML 1.2
---

ner:
    tokenizer: spacy

tokenizer:
    bert_model_name: bert-base-uncased
    do_lower_case: 1
    stopwords_path: config/en_stopwords.txt

model:
    device: "cpu"
    max_seq_len: 20
    max_entity_types: 512

backend:
    type: shell
    url_rule: /robot/api/query
    methods:
        - POST
    port: 5000

topic_switch:
    strategy: queue # switch strategy, queue, current

timeout: 300 # seconds for session timeout

skills:
    faq1:
        wrapper: RuleResponse
        dialogflow: data/FAQs.xlsx
        w2v_word2idx: data/word2vec/en/bert-base-uncased.lookup 
        w2v_idx2vec: data/word2vec/en/bert-base-uncased.h5py 
        prefilter: 500
        score_tolerate: 0.05
        min_score: 0.7
        believe_score: 0.85
        confuse_reply: "Sorry I'm confused about your question, could you please type the correct ID of following question list?"

    faq2:
        wrapper: RuleResponse
        dialogflow: data/elsa.xlsx
        w2v_word2idx: data/word2vec/en/bert-base-uncased.lookup 
        w2v_idx2vec: data/word2vec/en/bert-base-uncased.h5py 
        prefilter: 500
        score_tolerate: 0.05
        min_score: 0.85
        believe_score: 0.85

    cornell: 
        wrapper: GenerativeResponse
        beam_size: 5
        saved_model: data/cornell/cornell.pt


