%YAML 1.2
---
#app setting
APPNAME: END2END_DEMO

response_template: 
    data: data/template.txt
    cached_index: data/template.index


ner:
    LANGUAGE: en
    TOKENIZER: spacy
    stopwords_path: config/en_stopwords.txt
    ner_name_replace:
        person_name: PERSON
        company_name: ORG
        product_name: PRODUCT
        org_name: NORP
        location: LOC
        time: TIME
    ner:
    keywords:
        USAGE: config/usage.txt
        CERTIFICATION: config/certification.txt
        COUNTRY: config/country.txt
    regex:  
        #EMAIL: '[a-zA-Z\d\.\-]+@[a-zA-Z\d\.\-]+(\.[a-zA-Z\d]{2,3}){1,2}'
        WBS: '(\d{1,3}x\d{1,3})|(a\d{6})'
        EID: '(?<=\s)[a-z]{1,10}(\.[a-z]{1,10}){1,3}(?=[\s\.])'
        #DATE: '(\d{2,4}年)?\d{1,2}月\d{1,2}[日号]|(\d{2,4}\-)?\d{1,2}\-\d{1,2}|(\d{2,4}\.)?\d{1,2}\.\d{1,2}|(\d{2,4}\/)?\d{1,2}\/\d{1,4}'
        #NUMBER: '\d{1,5}(\,\d{1,5})?'


model:
    use_gpu: False
    learning_rate: 0.001
    weight_decay: 0.0001
    epochs: 100
    saved_model: 'data/model.pt'

logger:
    LogLevel_Console:  10
    LogLevel_File: 0
    LogFile: /tmp/train.log
    LogFormat: '%(asctime)s | %(levelname)s: %(message)s'

