%YAML 1.2
---
#app setting
APPNAME: END2END_DEMO

response_template: 
    data: data/template.txt
    cached_index: data/template.index

entity_dict: data/entity.dict

ner:
    LANGUAGE: en
    TOKENIZER: spacy
    w2v_word2idx: /home/pzhu/data/word2vec/en/word2idx_2000000.pp
    w2v_idx2vec: /home/pzhu/data/word2vec/en/weight_2000000.npy
    cached_vocab: data/vocab_en.pkl
    vocab_size: 100000
    cached_w2v: data/w2v_en.pkl
    vec_len: 300
    annoy_filter: 0.8
    stopwords_path: config/en_stopwords.txt
    ner_name_replace:
        person_name: PERSON
        company_name: ORG
        product_name: PRODUCT
        org_name: NORP
        location: LOC
        time: TIME
    ner:
    keywords:
        USAGE: config/entities/usage.txt
        USAGE_LETTER: config/entities/usage_letter.txt
        USAGE_LETTER2: config/entities/usage_letter2.txt
        USAGE_EMPLOYMENT: config/entities/usage_employment.txt
        USAGE_WBS: config/entities/usage_wbs.txt
        USAGE_LEAVE: config/entities/usage_leave.txt
        USAGE_REASON: config/entities/reason.txt
        LANGUAGE: config/entities/language.txt
        LETTER_TYPE: config/entities/letter_type.txt
        COUNTRY: config/entities/country.txt
    regex:  
        EMAIL: '[a-zA-Z\d\.\-]+@[a-zA-Z\d\.\-]+(\.[a-zA-Z\d]{2,3}){1,2}'
        PASSPORT: 'G\d{8}'
        WBS: '(\d{1,3}x\d{1,3})|(a\d{6})'
        EID: '(?<=\s)[a-z]{1,10}(\.[a-z]{1,10}){1,3}(?=[\s\.])'
        DATE: '(\d{2,4}年)?\d{1,2}月\d{1,2}[日号]|(\d{2,4}\-)?\d{1,2}\-\d{1,2}|(\d{2,4}\.)?\d{1,2}\.\d{1,2}|(\d{2,4}\/)?\d{1,2}\/\d{1,4}'
        #NUMBER: '\d{1,5}(\,\d{1,5})?'


model:
    use_gpu: 2
    max_seq_len: 10
    max_entity_len: 20
    dropout: 0.5
    cnn_kernel_size: 5
    cnn_kernel_num: 64
    learning_rate: 0.001
    weight_decay: 0.0001
    epochs: 100
    batch_size: 30
    saved_model: 'data/model.pt'

logger:
    LogLevel_Console:  10
    LogLevel_File: 0
    LogFile: data/hr_train.log
    LogFormat: '%(asctime)s | %(levelname)s: %(message)s'

