%YAML 1.2
---


# for adversary chatbot
dialog_file: data/babi/babi_adversary.xlsx 


tokenizer:
    tokenizer: spacy
    spacy_model: en
  
embedding:
    w2v_word2idx: /home/pzhu/data/word2vec/en/word2idx_2000000.pp
    w2v_idx2vec: /home/pzhu/data/word2vec/en/weight_2000000.npy

vocab:
    cached_vocab: data/babi/vocab_adversary.pkl

hook_keywords:
    PARTY_SIZE: data/babi/entities/party_size.txt
    LOCATION: data/babi/entities/location.txt
    CUISINE: data/babi/entities/cuisine.txt
    REST_TYPE: data/babi/entities/rest_type.txt

logger:
    LogLevel_Console:  20
    LogLevel_File: 0
    LogFile: data/babi/train.log
    LogFormat: '%(asctime)s | %(levelname)s: %(message)s'
